### PR TITLE
Ok 38 make recommendations similar to a users likes

### PR DESCRIPTION
**Pull request by ClementCadieux**
Jira: https://champlainsaintlambert.atlassian.net/jira/software/projects/OK/boards/55?selectedIssue=OK-38

Context: The API now gives movies based on a user's reviews of other movies.

Changes:
Created Repository and Service objects to call outside systems such as the database and the TMDB API
Calculates the highest recommended movie based on TMDB Api recommendations.

Note: Recommended movies aren't compared to the DB, as we don'T have enough movie for it to be viable. Once more movies are added, this will be changed (commented out code)

### CODE REVIEW

**Comment by dufourmax1738** [comment]
Nicely done but could you add the jira Id to the PR for later reference.

**Review by DuncanBH — APPROVED** [review]
Looks good to me.

You mentioned not having enough movies in the DB, would there be a way to procedurally add them as missing movies are found? or is this not worth the effort or the risk of overloading the DB?

**Comment by ClementCadieux** [comment]
> Nicely done but could you add the jira Id to the PR for later reference.

I forgot that! Doing it right now.

**Comment by ClementCadieux** [comment]
> Looks good to me.
> 
> You mentioned not having enough movies in the DB, would there be a way to procedurally add them as missing movies are found? or is this not worth the effort or the risk of overloading the DB?

This is gonna be in the future plans for sure. We fortunately have most of the code for this already written in our dummy-data-collection repository.

**Pull request merged**
